package xmx.model;
// Generated 2017-11-24 11:58:50 by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private Integer state;
     private Date createTime;

    public Admin() {
    }

	
    public Admin(String username, String password, Date createTime) {
        this.username = username;
        this.password = password;
        this.createTime = createTime;
    }
    public Admin(String username, String password, Integer state, Date createTime) {
       this.username = username;
       this.password = password;
       this.state = state;
       this.createTime = createTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


