package xmx.model;
// default package
// Generated 2017-11-24 11:58:50 by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String target;
     private String method;
     private String param;
     private String user;
     private String userType;
     private String ip;
     private Date createTime;

    public Log() {
    }

	
    public Log(Date createTime) {
        this.createTime = createTime;
    }
    public Log(String type, String target, String method, String param, String user, String userType, String ip, Date createTime) {
       this.type = type;
       this.target = target;
       this.method = method;
       this.param = param;
       this.user = user;
       this.userType = userType;
       this.ip = ip;
       this.createTime = createTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getTarget() {
        return this.target;
    }
    
    public void setTarget(String target) {
        this.target = target;
    }
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }
    public String getParam() {
        return this.param;
    }
    
    public void setParam(String param) {
        this.param = param;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


