package xmx.model;
// default package
// Generated 2017-11-24 11:58:50 by Hibernate Tools 5.2.6.Final


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String phone;
     private String email;
     private String birthday;
     private String sex;
     private int state;
     private Date createTime;

    public User() {
    }

	
    public User(String username, String password, int state, Date createTime) {
        this.username = username;
        this.password = password;
        this.state = state;
        this.createTime = createTime;
    }
    public User(String username, String password, String phone, String email, String birthday, String sex, int state, Date createTime) {
       this.username = username;
       this.password = password;
       this.phone = phone;
       this.email = email;
       this.birthday = birthday;
       this.sex = sex;
       this.state = state;
       this.createTime = createTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


